backgroundをScss記法に変更、h2:beforeをScss記法に変更
Kuma-inataku/tenkue-app-r005 pull request #7
Opened 2020-10-24 06:29 UTC by Kuma-inataku

修正完了です。すいません。
昨日作業したところに戻りました。

2020-10-24 08:17 UTC, ToshifumiIde requested changes
ローカルに別ディレクトリを作成して作業されていたため、background-imageの相対パスが全てうまく紐づいていません。
background:url(../../../../asset/image/......(必要な画像のファイル名))
など、より階層を上がっていただく必要があります。
また、heightの指定をされていませんが、ご参考までに

height:60vh;

をお試しください。
ローカルに落としてサーバーで立ち上げてみた結果その他の発見もございますが、現状ではこのご対応をいただければと思います。

2020-10-24 08:17 UTC, ToshifumiIde commented on src/asset/sass/object/project/_contact.scss
> +  background:$color-primary;
ここの色に関しては_baase.scssに変数で色は登録されていないので、
#E8E1D3
で変更しなくて構いません。

2020-10-24 08:17 UTC, ToshifumiIde commented on src/asset/sass/object/project/_contact.scss
> +      background:$color-primary;
ここの色に関しては_baase.scssに変数で色は登録されていないので、
#E8E1D3
で変更しなくて構いません。

2020-10-24 10:51 UTC, Kuma-inataku commented
遅れて大変申し訳ございません。
ご指摘いただいた内容について、修正しました。
ご確認のほどよろしくお願いいたします。

2020-10-24 11:09 UTC, ToshifumiIde reviewed
ご対応ありがとうございました。

2020-10-24 11:09 UTC, ToshifumiIde approved these changes
ご対応ありがとうございました。
Approveいたします。

2020-10-24 11:42 UTC, Kuma-inataku commented
conflict対応完了しました

2020-10-24 11:49 UTC, okateru0217 approved these changes

2020-10-24 11:49 UTC, okateru0217 commented on src/asset/sass/object/project/_contact.scss
>    color:white;
色を指定する際、「16進数表記」と「カラー名表記」のどちらかで統一した方が綺麗かと思いますが、いかがでしょう。
今回であれば、「white」を「#ffffff」で指定すれば問題ないと思います。

2020-11-07 10:24 UTC, Taka-hyt approved these changes

2020-11-07 10:30 UTC, merged